import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "@/app/globals.css";

import { AppSidebar } from "@/components/dashboard/Sidebar";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "LOKERIN | LAMAR OTOMATIS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900 text-neutral-100`}
      >
        <SidebarProvider>
          <AppSidebar />

          {/* SidebarInset = wrapper agar sidebar bisa geser di mobile */}
          <SidebarInset>
            {/* Tombol hamburger muncul di mobile */}
            <div className="p-4 border-b border-neutral-800 flex items-center lg:hidden">
              <SidebarTrigger />
              <h1 className="font-semibold text-lg ml-2">LOKERIN</h1>
            </div>

            {/* Konten */}
            <main className="p-6 ">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
