import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "@/app/globals.css";

import { AppSidebar } from "@/components/dashboard/Sidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";

import Header from "@/components/dashboard/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "LOKERIN | LAMAR OTOMATIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900 text-neutral-100`}
      >
        <SidebarProvider>
          <AppSidebar />

          <SidebarInset>
            {/* HEADER DASHBOARD */}
            <Header />

            {/* CONTENT */}
            <main className="p-4 bg-[#F5F5F5]">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
